### ISSUE TITLE
Remove KnowledgeTree Code

### ISSUE THREAD

**Issue by jvandyke** [stelligent/asgard-in-the-cloud#3]
Hi @stelligent. Some KnowledgeTree-specific code was pull in your repo from a PR. Can you please rebase the code from commit 54f925f2a982c6267dddbb83f7bd3230b684cf81 out of your codebase? We will resubmit a proper PR.

Sorry and thanks

**Comment by jsywulak** [comment]
I've pruned out all the Knowledge Tree code. Lesson learned: don't review pull requests before coffee. :)

**Comment by jvandyke** [comment]
Hah! Thanks. Looks like the commit history and code still exists. Would you mind deleting those entries from history or is that too much? It's not confidential info, just the full names of some of our employees and some public ssh keys, which weirds me out.

**Comment by jsywulak** [comment]
Alright, using my limited git knowledge I was able to clean out what I could find. I was able to shred all the keys and references to names that I found, let me know if I missed any.

**Comment by jvandyke** [comment]
Looks good, I can't find a trace of our org or names in the current code and the offending commits appear to have been redacted. Thanks, @jsywulak!
